trigger:
  branches:
    include:
      - main  # Substitua por sua branch principal

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '20'  # Substitua pela versão do Node.js que você está usando
  displayName: 'Install Node.js'
- script: |
    npm
    npm build
  displayName: 'Install dependencies and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish Artifacts'
- task: AzureStaticWebApp@0
  inputs:
    azure_static_web_apps_api_token: $(deployment_token)
    app_location: '/'
    api_location: 'api'  # Se você tiver uma API
    output_location: 'build'
  displayName: 'Deploy to Azure Static Web App'