openapi: 3.0.3
info:
  title: FX Token API
  version: 1.0.0
  description: |
        This is a server-to-server operation that retrieves a token to be used
        in fixed exchange rate operations.

        The integration team should be contacted to enable it upon request to
        use this feature.
servers:  
  - url: 'https://sandbox.ebanxpay.com/'
    description: Sandbox API Server
  - url: 'https://api.ebanxpay.com/'
    description: Production API Server
paths:
  /ws/fxtoken/get:
    post:
      summary: Get FX Token
      description: Retrieves a foreign exchange token along with the current exchange rate and related details.
      requestBody:
        description: Request body for retrieving the FX token and currency rate.
        content:
          application/json:
            schema:
              type: object
              properties:
                country:
                  type: string
                  nullable: true
                  maxLength: 2
                  minLength: 2
                  description: | 
                    Optional country code for regional settings.
                    string 2 characters
                    Enum: "br" "pe" "mx" "co" "cl" "ar" "bo"
                    The two-letter code for the country where the operation is being processed. The available codes are:

                    br: Brazil.
                    pe: Peru.
                    mx: Mexico.
                    co: Colombia.
                    cl: Chile.
                    ar: Argentina.
                    bo: Bolivia.

                integration_key:
                  type: string
                  description: Integration key for authentication. Your unique and secret integration key.
                  maxLength: 100
                currency_from:
                  type: string
                  maxLength: 3
                  minLength: 3
                  description: | 
                      Currency code to convert from (e.g., USD).
                      Enum: "EUR" "USD"
                      The three-letter currency code from which the amount will be converted. Supported currencies:

                      EUR
                      USD
                currency_to:
                  type: string
                  maxLength: 3
                  minLength: 3
                  description: | 
                      Currency code to convert to (e.g., PEN).
                      Enum: "BRL" "MXN" "PEN" "CLP" "COP" "ARS" "BOB"
                      The three-letter currency code to which the amount will be converted. Supported currencies:

                      BRL
                      MXN
                      PEN
                      CLP
                      COP
                      ARS
                      BOB

              required:
                - integration_key
                - currency_from
                - currency_to
              example:
                country: null
                integration_key: "12345678910ABCDED945464"
                currency_from: "USD"
                currency_to: "PEN"
        required: true
      responses:
        '200':
          description: Successful response with FX token and currency rate.
          content:
            application/json:
              schema:
                type: object
                properties:
                  fx_token:
                    type: string
                    description: Token for foreign exchange request. The token identifier that must be used in operations with the fixed exchange rate.
                    maxLength: 100
                  currency_rate:
                    type: string
                    description: Exchange rate between the provided currencies.The fixed exchange rate that will be used in operations where this token is provided.
                  currency_from:
                    type: string
                    description: Currency code from which the conversion is made. The fixed exchange rate that will be used in operations where this token is provided.
                    minLength: 3
                    maxLength: 3
                  currency_to:
                    type: string
                    description: Currency code to which the conversion is made. The same three-letter code provided in the request. Format ISO 4217 three letter code.
                    minLength: 3
                    maxLength: 3
                  expire_date:
                    type: string
                    format: date-time
                    description: The date and time when the FX token expires. The date in which the token will become invalid. UTC Date.
                    minLength: 25
                    maxLength: 25
                  new_currency_rate_available_at:
                    type: string
                    format: date-time
                    description: The date and time when a new currency rate will be available. The date on which the next token will become available. A new token will always be available at least one hour before the expire_date of the previous token. During this period both new and old tokens will be valid. UTC Date.
                    minLength: 25
                    maxLength: 25
                example:
                  fx_token: "66e77536521b31b59678d8bcb48c0d0bde18d4490ad52ac656"
                  currency_rate: "3.7833"
                  currency_from: "USD"
                  currency_to: "PEN"
                  expire_date: "2024-09-16T13:59:59+00:00"
                  new_currency_rate_available_at: "2024-09-16T13:44:59+00:00"
