openapi: 3.0.3
info:
  title: Payment API for OXXOPAY MX
  description: API for processing payments - OXXOPAY MX
  version: 1.0.0
servers:
servers:
  - url: https://sandbox.empresa.com
    description: Sandbox API Server
  - url: https://prod.empresa.com
    description: Production API Server
paths:
  /ws/direct:
    post:
      summary: Process a payment OXXO MX
      description: Request a payment transaction
      operationId: requestPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mode:
                  type: string
                  example: full
                operation:
                  type: string
                  example: request
                payment:
                  type: object
                  properties:
                    amount_total:
                      type: string
                      example: "763.19"
                    country:
                      type: string
                      example: MX
                    currency_code:
                      type: string
                      example: MXN
                      description: Currency.
                      required: true
                    email:
                      type: string
                      example: people@mail.com
                    merchant_payment_code:
                      type: string
                      example: 11111111111111111
                    name:
                      type: string
                      example: Gustavo garcia
                    payment_type_code:
                      type: string
                      example: oxxopay
                integration_key:
                  type: string
                  example: AAAAAAAAAAAAAAAAAAA
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  payment:
                    type: object
                    properties:
                      hash:
                        type: string
                        example: 77e1501f2668c80dda0cf099db75d1dff559eede892c799f
                      country:
                        type: string
                        example: mx
                      merchant_payment_code:
                        type: string
                        example: 123581321345589
                      order_number:
                        type: string
                        nullable: true
                        example: null
                      status:
                        type: string
                        example: PE
                      status_date:
                        type: string
                        nullable: true
                        example: null
                      open_date:
                        type: string
                        example: 2020-08-29 11:48:47
                      confirm_date:
                        type: string
                        nullable: true
                        example: null
                      transfer_date:
                        type: string
                        nullable: true
                        example: null
                      amount_br:
                        type: string
                        example: "763.19"
                      amount_ext:
                        type: string
                        example: "763.19"
                      amount_iof:
                        type: string
                        example: "0.00"
                      amount_ext_requested:
                        type: string
                        example: "763.19"
                      currency_rate:
                        type: string
                        example: "1.0000"
                      currency_ext:
                        type: string
                        example: MXN
                      due_date:
                        type: string
                        example: 2020-09-01
                      instalments:
                        type: string
                        example: "1"
                      payment_type_code:
                        type: string
                        example: oxxopay
                      voucher_url:
                        type: string
                        example: https://print.aaaaaa.com/print/voucher/execute?hash=aaaaaa11111222
                      pre_approved:
                        type: boolean
                        example: false
                      capture_available:
                        type: string
                        nullable: true
                        example: null
                      oxxopay_barcode:
                        type: string
                        example: 12345697891
                  status:
                    type: string
                    example: SUCCESS
