openapi: 3.0.3
info:
  title: Payment API for PIX BR
  description: API for processing payments PIX in Brazil. This method allows you to create a payment using Empresa Payment Page, where the customer is redirected to Empresa website to enter his data.
  version: 1.0.0
servers:
  - url: https://sandbox.empresa.com
    description: Sandbox API Server
  - url: https://prod.empresa.com
    description: Production API Server
paths:
  /ws/direct:
    post:
      summary: Process a payment PIX BR
      description: Process a payment PIX BR
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                integration_key:
                  type: string
                  title: 1 Your unique and secret integration key.
                  description: Your unique and secret integration key.
                  example: 'your-integration-key-here'
                  required: true
                  minLength: 1    
                  maxLength: 100
                metadata:
                  type: object
                  properties:
                    risk:
                      type: object
                      properties:
                        customer_account_create_date:
                          type: string
                          format: date
                          example: '2018-12-12'
                        customer_account_create_type:
                          type: string
                          example: 'facebook'
                        seller_information:
                          type: object
                        shipping_info:
                          type: object
                          properties:
                            shipping_amount:
                              type: number
                              format: float
                              example: 0.00
                            type:
                              type: string
                              example: 'Minimum Shipping Fee'
                  required:
                    - risk
                operation:
                  type: string
                  description: Must be request
                  minLength: 7
                  maxLength: 7
                  example: 'request'
                  required: true
                payment:
                  type: object
                  properties:
                    address:
                      type: string
                      description: Customer address (street name).
                      example: '123 Main Street, Apartment 101'
                      minLength: 1    
                      maxLength: 100
                    amount_total:
                      type: number
                      format: float
                      example: 211.28
                    city:
                      type: string
                      description: Customer city.
                      example: 'Cascavel'
                      minLength: 1    
                      maxLength: 80
                    country:
                      type: string
                      description: string 3 characters. Enum "BRL" "EUR" "MXN" "PEN" "USD" "CLP" "COP" "ARS" "BOB" "UYU" Three-letter code of the payment currency.
                      example: 'BR'
                    currency_code:
                      type: string
                      example: 'BRL'
                    document:
                      type: string
                      description: Customers document. Brazil requires a valid CPF (natural person taxpayer ID) or CNPJ (business taxpayer ID). 
                      example: '123.456.789-00'   
                      maxLength: 32
                    email:
                      type: string
                      description: Customer email address.
                      example: 'example@example.com'
                      minLength: 1    
                      maxLength: 100
                    expiration_time_in_seconds:
                      type: integer
                      example: 86400
                    items:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          description:
                            type: string
                            example: 'SHEGLAM Pink Primer Facial, Hydrating Primer, Invisible Pore Corrector, Rose Essential Oil, For Daily Skincare'
                          name:
                            type: string
                            example: 'SHEGLAM Pink Primer Facial, Hydrating Primer, Invisible Pore Corrector, Rose Essential Oil, For Daily Skincare'
                          quantity:
                            type: integer
                            example: 1
                          seller_id:
                            type: string
                            example: 'SELLER123'
                          sku:
                            type: string
                            example: 'sku123456'
                          store_id:
                            type: string
                            example: 'store1'
                          unit_price:
                            type: number
                            format: float
                            example: 211.28
                    merchant_payment_code:
                      type: string
                      example: 'MERCHANTCODE123456'
                    name:
                      type: string
                      description: Customer name.
                      example: 'John Doe'
                      minLength: 1    
                      maxLength: 100
                    order_number:
                      type: string
                      example: 'ORDER123456'
                    payment_type_code:
                      type: string
                      example: 'pix'
                    phone_number:
                      type: string
                      example: '1234567890'
                    single_transaction:
                      type: object
                      properties:
                        amount_crossborder:
                          type: number
                          format: float
                          example: 211.28
                        amount_local:
                          type: number
                          format: float
                          example: 0.00
                    state:
                      type: string
                      example: 'PR'
                      description: Customer state/region/province. If Brazil "AC" "AL" "AP" "AM" "BA" "CE" "DF" "ES" "GO" "MA" "MT" "MS" "MG" "PA" "PB" "PR" "PE" "PI" "RJ" "RN" "RS" "RO" "RR" "SC" "SP" "SE" "TO".
                    street_number:
                      type: string
                      description: Customer street number.
                      example: '123 Main Street'
                      minLength: 1    
                      maxLength: 30
                    zipcode:
                      type: string
                      description: Customer’s zipcode. Brazil required.
                      example: '12345-678'
                      minLength: 1    
                      maxLength: 8
                  required:
                    - address
                    - amount_total
                    - city
                    - country
                    - currency_code
                    - document
                    - email
                    - expiration_time_in_seconds
                    - items
                    - merchant_payment_code
                    - name
                    - order_number
                    - payment_type_code
                    - phone_number
                    - single_transaction
                    - state
                    - street_number
                    - zipcode
              required:
                - integration_key
                - metadata
                - operation
                - payment
      responses:
        '200':
          description: Successful response (either success or error with HTTP 200)
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/PIXBRSuccessResponse'
                  - $ref: '#/components/schemas/PSECOSuccessResponse'
                  - $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    PSECOSuccessResponse:
      type: object
      properties:
        payment:
          type: object
          properties:
               hash:
                  type: string
                  description: Payment hash for verification
                  example: "aaaa222aaassasbbb333333"
                country:
                  type: string
                  description: Country of the payment
                  example: "co"
                merchant_payment_code:
                  type: string
                  description: Merchant payment code
                  example: "aa"
                order_number:
                  type: string
                   description: Order number
                  example: "2121212121CCC"
                status:
                  type: string
                  description: Payment status
                  example: "PE"
                status_date:
                  type: string
                  format: date-time
                  description: Date when the status was set
                  example: null
                open_date:
                  type: string
                  format: date-time
                  description: Date when the payment was opened
                  example: "2024-09-04 12:15:21"
                confirm_date:
                  type: string
                  format: date-time
                  description: Date when the payment was confirmed
                  example: null
                transfer_date:
                  type: string
                  format: date-time
                  description: Date when the payment was transferred
                  example: null
                amount_br:
                  type: number
                  format: float
                  description: Amount in local currency
                  example: 204958.00
                amount_ext:
                  type: number
                  format: float
                  description: Amount in external currency
                  example: 204958.00
                amount_iof:
                  type: number
                  format: float
                  description: Amount of IOF (Tax)
                  example: 0.00
                currency_rate:
                  type: string
                  description: Currency rate used
                  example: "1.0000"
                currency_ext:
                  type: string
                  description: External currency code
                  example: "COP"
                due_date:
                  type: string
                  format: date-time
                  description: Due date for the payment
                  example: "2024-09-05 12:15:21"
                instalments:
                  type: string
                  description: Number of instalments
                  example: "1"
                payment_type_code:
                  type: string
                  description: Payment type code
                  example: "eft"
                redirect_url:
                  type: string
                  description: URL to redirect after payment
                  example: "https://api.aaaaaa.com/ws/redirect/execute?hash=6aaa12121212121"
                pre_approved:
                  type: boolean
                  description: Indicates if the payment was pre-approved
                  example: false
                capture_available:
                  type: string
                  description: Indicates if capture is available
                  example: null
                status:
                  type: string
                  description: Response status
                  example: "SUCCESS"
                redirect_url:
                  type: string
                  description: URL to redirect for further action
                  example: "https://api.aaaaaa.com/ws/redirect/execute?hash=abbb1111aaaaaaaa"                   
    PixBRSuccessResponse:
      type: object
      properties:
        payment:
          type: object
          properties:
            hash:
              type: string
              example: 'hash-value-placeholder'
            country:
              type: string
              example: 'br'
            merchant_payment_code:
              type: string
              example: 'MERCHANTCODE123456'
            order_number:
              type: string
              example: 'ORDER123456'
            status:
              type: string
              example: 'PE'
            open_date:
              type: string
              format: date-time
              example: '2024-09-03T10:49:40Z'
            confirm_date:
              type: string
              format: date-time
              example: 'null'
            transfer_date:
              type: string
              format: date-time
              example: 'null'
            amount_br:
              type: string
              example: '212.08'
            amount_ext:
              type: string
              example: '211.28'
            amount_iof:
              type: string
              example: '0.80'
            currency_rate:
              type: string
              example: '1.0000'
            currency_ext:
              type: string
              example: 'BRL'
            due_date:
              type: string
              format: date
              example: '2024-09-04'
            instalments:
              type: string
              example: '1'
            payment_type_code:
              type: string
              example: 'pix'
            redirect_url:
              type: string
              format: uri
              example: 'https://example.com/pix/checkout?hash=hash-value-placeholder'
            pre_approved:
              type: boolean
              example: false
            capture_available:
              type: string
              example: 'null'
            pix:
              type: object
              properties:
                qr_code_value:
                  type: string
                  example: 'aaaaaaaaaa.gov.bcb.bbbbbb.ccccccc.com/qr/v2/qr-code-placeholder'
            single_transaction:
              type: object
              properties:
                amount_local:
                  type: string
                  example: '0.00'
                amount_crossborder:
                  type: string
                  example: '212.08'
          required:
            - hash
            - country
            - merchant_payment_code
            - order_number
            - status
            - open_date
            - amount_br
            - amount_ext
            - amount_iof
            - currency_rate
            - currency_ext
            - due_date
            - instalments
            - payment_type_code
            - redirect_url
            - pre_approved
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: string
              example: 'ERROR'
              description: ERROR
            status_code:
              type: string
              example: 'BP-DR-23'
              description: Code of error.
            status_message:
              type: string
              example: 'Field payment.document must be a valid CPF'
              description: Message about error.
          required:
            - status
            - status_code
            - status_message
      required:
        - error