openapi: 3.0.3
info:
  title: Search Transfer Requests
  description: This method allows you to retrieve multiple transfers information.
  version: 1.0.0
servers:
  - url: 'https://sandbox.ebanxpay.com/'
    description: Sandbox API Server
  - url: 'https://api.ebanxpay.com/'
    description: Production API Server       
paths:
  /ws/transfer/search:
    post:
      summary: Search Transfer Requests
      description: This method allows you to retrieve information about multiple transfers.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Request'

      responses:
        200:
          description: Response Payout
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/SuccessResponse'
        400:
          description: Response Payout
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorResponse'   
      
components:
  schemas:
    Request:
              type: object
              required:
                - integration_key
                - date_from
                - date_to
              properties:
                integration_key:
                  type: string
                  description: Your unique and secret integration key.
                  maxLength: 100
                  example: your_test_integration_key
                date_from:
                  type: string
                  description: Initial date in the format yyyy-mm-dd.
                  example: "1977-05-25"
                date_to:
                  type: string
                  description: End date in the format yyyy-mm-dd.
                  example: "1977-05-26"
                page:
                  type: integer
                  description: The page number of the current search.
                  example: 2
                status:
                  type: string
                  description: The transfer status.
                  enum:
                    - CA
                    - OP
                    - PA
                  example: OP
                per_page:
                  type: integer
                  description: Max number of transfers per page (API Max 50).
                  example: 20
  
    SuccessResponse:
                type: object
                properties:
                  type:
                    type: string
                    description: The type of the response.
                    example: success
                  records:
                    type: integer
                    description: Total number of records.
                    example: 2
                  total_pages:
                    type: integer
                    description: Total number of pages.
                    example: 1
                  per_page:
                    type: integer
                    description: Number of transfers per page.
                    example: 50
                  page:
                    type: integer
                    description: Number of the current page.
                    example: 1
                  transfers:
                    type: array
                    items:
                      type: object
                      properties:
                        uid:
                          type: string
                          description: The transfer unique identifier.
                          example: "11ce3097af9ccf601b11038767962d3feded348aa"
                        external_reference:
                          type: string
                          description: The unique transfer ID provided by the client.
                          minLength: 6
                          maxLength: 40
                          example: "PAYOUT_TRANSFER_01"
                        status:
                          type: string
                          description: The transfer status.
                          enum:
                            - OP
                            - PA
                            - CA
                          example: OP
                        request_date:
                          type: string
                          description: The date and hour of when the transfer was requested. UTC Date.
                          example: "2017-02-08 17:33:56"
                        confirm_date:
                          type: string
                          description: The date and hour of when the transfer was confirmed. UTC Date.
                          nullable: true
                          example: null
                        cancel_date:
                          type: string
                          description: The date and hour of when the transfer was cancelled. UTC Date.
                          nullable: true
                          example: null
                        amount:
                          type: string
                          description: The transfer amount.
                          example: "100.00"
                        transfer_code:
                          type: string
                          description: The unique identifier to be used during the bank transfer (for wire transfers).
                          example: "14-2000"
                        settlement_code:
                          type: string
                          description: The settlement when the transfer was debited (for transfers using Payment Balance).
                          nullable: true
                          example: null
                        source:
                          type: string
                          description: The transfer source.
                          enum:
                            - payment_balance
                            - wire_transfer
                          example: wire_transfer
    
    ErrorResponse:                          
                type: object
                properties:
                  type:
                    type: string
                    description: Type of the error.
                    example: invalid_request_error
                  message:
                    type: string
                    description: Error message describing the issue.
                    example: Invalid Expression
                  status_code:
                    type: string
                    description: Status code of the error.
                    example: HP-DF-02
                  code:
                    type: string
                    description: Specific error code.
                    example: HP-DF-02
