openapi: 3.0.0
info:
  title: Payment API for PSE CO
  description: API for processing PSE CO.
  version: 1.0.0
paths:
  /payment:
    post:
      summary: Process a payment request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                integration_key:
                  type: string
                  description: Integration key for authentication
                  example: "************************AKHY0g"
                operation:
                  type: string
                  description: Operation type
                  example: "request"
                payment:
                  type: object
                  properties:
                    address:
                      type: string
                      description: Shipping address
                      example: "Calle 8 #11-77 Barrio el Carmen"
                    amount_total:
                      type: number
                      format: float
                      description: Total amount for the payment
                      example: 204958.00
                    city:
                      type: string
                      description: City of the payment address
                      example: "Curumani"
                    country:
                      type: string
                      description: Country of the payment address
                      example: "CO"
                    currency_code:
                      type: string
                      description: Currency code
                      example: "COP"
                    eft_code:
                      type: string
                      description: EFT payment code
                      example: "nequi"
                    email:
                      type: string
                      description: Email address of the payer
                      example: "foooo@mymailfooo.com"
                    items:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          description:
                            type: string
                            description: Description of the item
                            example: "50 piezas de acrílico..."
                          name:
                            type: string
                            description: Name of the item
                            example: "50 piezas de acrílico..."
                          quantity:
                            type: integer
                            description: Quantity of the item
                            example: 2
                          sku:
                            type: string
                            description: Stock Keeping Unit (SKU)
                            example: "sh2403089366204260"
                          unit_price:
                            type: number
                            format: float
                            description: Unit price of the item
                            example: 28190.0
                    merchant_payment_code:
                      type: string
                      description: Merchant payment code
                      example: "AAA111BBB222CCC333"
                    name:
                      type: string
                      description: Name of the payer
                      example: "Foo Name surename"
                    order_number:
                      type: string
                      description: Order number
                      example: "A1B2C3D4F5E6"
                    payment_type_code:
                      type: string
                      description: Payment type code
                      example: "eft"
                    phone_number:
                      type: string
                      description: Phone number of the payer
                      example: "1111111111"
                    redirect_url:
                      type: string
                      description: URL to redirect after payment
                      example: "https://example.com/redirect"
                    state:
                      type: string
                      description: State of the payment address
                      example: "Cesar"
                    street_number:
                      type: string
                      description: Street number of the payment address
                      example: "Calle 8 #11-77 Barrio el Carmen"
                    zipcode:
                      type: string
                      description: ZIP code of the payment address
                      example: "203060"
      responses:
        '200':
          description: Successful payment request
          content:
            application/json:
              schema:
                type: object
                properties:
                  payment:
                    type: object
                    properties:
                      hash:
                        type: string
                        description: Payment hash for verification
                        example: "aaaa222aaassasbbb333333"
                      country:
                        type: string
                        description: Country of the payment
                        example: "co"
                      merchant_payment_code:
                        type: string
                        description: Merchant payment code
                        example: "aa"
                      order_number:
                        type: string
                        description: Order number
                        example: "2121212121CCC"
                      status:
                        type: string
                        description: Payment status
                        example: "PE"
                      status_date:
                        type: string
                        format: date-time
                        description: Date when the status was set
                        example: null
                      open_date:
                        type: string
                        format: date-time
                        description: Date when the payment was opened
                        example: "2024-09-04 12:15:21"
                      confirm_date:
                        type: string
                        format: date-time
                        description: Date when the payment was confirmed
                        example: null
                      transfer_date:
                        type: string
                        format: date-time
                        description: Date when the payment was transferred
                        example: null
                      amount_br:
                        type: number
                        format: float
                        description: Amount in local currency
                        example: 204958.00
                      amount_ext:
                        type: number
                        format: float
                        description: Amount in external currency
                        example: 204958.00
                      amount_iof:
                        type: number
                        format: float
                        description: Amount of IOF (Tax)
                        example: 0.00
                      currency_rate:
                        type: string
                        description: Currency rate used
                        example: "1.0000"
                      currency_ext:
                        type: string
                        description: External currency code
                        example: "COP"
                      due_date:
                        type: string
                        format: date-time
                        description: Due date for the payment
                        example: "2024-09-05 12:15:21"
                      instalments:
                        type: string
                        description: Number of instalments
                        example: "1"
                      payment_type_code:
                        type: string
                        description: Payment type code
                        example: "eft"
                      redirect_url:
                        type: string
                        description: URL to redirect after payment
                        example: "https://api.aaaaaa.com/ws/redirect/execute?hash=6aaa12121212121"
                      pre_approved:
                        type: boolean
                        description: Indicates if the payment was pre-approved
                        example: false
                      capture_available:
                        type: string
                        description: Indicates if capture is available
                        example: null
                  status:
                    type: string
                    description: Response status
                    example: "SUCCESS"
                  redirect_url:
                    type: string
                    description: URL to redirect for further action
                    example: "https://api.aaaaaa.com/ws/redirect/execute?hash=abbb1111aaaaaaaa"
