openapi: 3.0.3
info:
  title: Cancel a Payout request.
  description: Within this end-point you will be able to cancel a payout using payouts's external_reference or its uid The payout has to be in a status equal to OP and within the cancellation time.
  version: 1.0.0
servers:
  - url: 'https://sandbox.ebanxpay.com/'
    description: Sandbox API Server
  - url: 'https://api.ebanxpay.com/'
    description: Production API Server  
paths:
  /ws/payout/cancel:
    post:
      summary: Cancel a Payout request
      description: Within this end-point you will be able to cancel a payout using payouts's external_reference or its uid. The payout has to be in a status equal to OP and within the cancellation time.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/RequestSucccess'

      responses:
        200:
          description: Response Payout
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ResponseSuccess'
        400:
          description: Response Payout
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorResponse'   
      
components:
  schemas:
    RequestSucccess:
              type: object
              required:
                - integration_key
              properties:
                integration_key:
                  type: string
                  description: "Your unique and secret integration key."
                  maxLength: 100
                external_reference:
                  type: string
                  description: "The unique payout ID provided by you."
                  minLength: 4
                  maxLength: 60
                uid:
                  type: string
                  description: "The payout uid (EBANX unique identifier)."
                  maxLength: 50
             

    ResponseSuccess:
                type: object
                properties:
                  type:
                    type: string
                    example: success
                  message:
                    type: string
                    example: "You've successfully cancelled your Payout!"

    ErrorResponse:
                type: object
                properties:
                  type:
                    type: string
                    example: request_error
                  message:
                    type: string
                    example: "Payout status different than OP"
                  status_code:
                    type: string
                    example: HP-CM-55
                  code:
                    type: string
                    example: HP-CM-55