openapi: 3.0.3
info:
  title: Query
  description: The query operation is a server-to-server HTTP POST used by the merchant website to query EBANX for information about a specific payment.
  version: 1.0.0
servers:
  - url: 'https://sandbox.ebanxpay.com/'
    description: Sandbox API Server
  - url: 'https://api.ebanxpay.com/'
    description: Production API Server       
paths:
  /ws/query:
    post:
      summary: Query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                integration_key:
                  type: string
                  maxLength: 100
                  description: Your unique and secret integration key.
                  example: "your_test_integration_key"
                hash:
                  type: string
                  minLength: 48
                  maxLength: 48
                  description: The payment hash (EBANX unique identifier). Required if merchant_payment_code not provided.
                  example: "5478ba283ef8674415082844ee14817376e49bb76aa9d4c7"
                merchant_payment_code:
                  type: string
                  minLength: 1
                  maxLength: 40
                  description: The payment hash Merchant Payment Code (unique merchant ID). Required if hash not provided.
                  example: "1416854121"
              required:
                - integration_key
      responses:
        '200':
          description: Successful response with payment details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    minLength: 5
                    maxLength: 7
                    description: The status of the request (SUCCESS or ERROR).
                    example: "SUCCESS"
                  payment:
                    type: object
                    properties:
                      hash:
                        type: string
                        minLength: 48
                        maxLength: 48
                        description: The payment hash (EBANX unique identifier).
                        example: "54737a76ffc1e5a520b0ed9062213a810ef41dae990184c7"
                      merchant_payment_code:
                        type: string
                        minLength: 1
                        maxLength: 40
                        description: The payment hash Merchant Payment Code (unique merchant ID).
                        example: "1416854121"
                      order_number:
                        type: string
                        minLength: 1
                        maxLength: 40
                        description: Optional identifier set by the merchant.
                        example: null
                      status:
                        type: string
                        minLength: 2
                        maxLength: 2
                        description: The payment status.
                        example: "CO"
                      status_date:
                        type: string
                        format: date-time
                        description: The date and hour of the last status change.
                        example: "2014-11-24 16:35:43"
                      open_date:
                        type: string
                        format: date-time
                        description: The date and hour when the payment was created.
                        example: "2014-11-24 16:35:34"
                      confirm_date:
                        type: string
                        format: date-time
                        description: The date and hour when the payment was confirmed.
                        example: "2014-11-24 16:35:43"
                      transfer_date:
                        type: string
                        format: date-time
                        description: The date and hour when the payment was settled.
                        example: null
                      amount_br:
                        type: number
                        description: The amount in local currency.
                        example: 352.50
                      amount_ext:
                        type: number
                        description: The amount in the original currency.
                        example: 150.00
                      amount_iof:
                        type: number
                        description: The tax amount in local currency (varies between countries).
                        example: 0.00
                      currency_rate:
                        type: number
                        description: The exchange rate used in the payment.
                        example: 2.3500
                      currency_ext:
                        type: string
                        minLength: 3
                        maxLength: 3
                        description: ISO 4217 three-letter code of the original currency.
                        example: "USD"
                      due_date:
                        type: string
                        format: date
                        description: Expiry date of the payment. Format dd/mm/yyyy
                        example: "2014-12-01"
                      instalments:
                        type: integer
                        description: Number of instalments for the payment.
                        example: 1
                      payment_type_code:
                        type: string
                        maxLength: 32
                        description: The code of the payment method.
                        example: "bradesco"
                      pre_approved:
                        type: boolean
                        description: Indicates if the payment is pre-approved.
                        example: false
                      capture_available:
                        type: boolean
                        description: Flag that shows if a payment is ready to be captured. Applies only to credit cards when auto_capture is set to false.
                        example: null
                      refunds:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              description: Refund identifier.
                              example: "9283"
                            merchant_refund_code:
                              type: string
                              description: Optional identifier set by the merchant for the refund.
                              example: null
                            status:
                              type: string
                              description: The status of the refund (e.g., RE).
                              example: "RE"
                            request_date:
                              type: string
                              format: date-time
                              description: The date and time when the refund was requested.
                              example: "2014-11-26 17:56:52"
                            amount_ext:
                              type: number
                              description: The amount of the refund in the original currency.
                              example: 100.00
                            description:
                              type: string
                              description: Reason for the refund.
                              example: "Order did not arrive"
                            settlement:
                              type: object
                              properties:
                                transfer_date:
                                  type: string
                                  format: date
                                  description: Date when the settlement was transferred.
                                  example: "2014-12-01"
                                amount:
                                  type: number
                                  description: Settlement amount.
                                  example: 100
                            refund_status_details:
                              type: object
                              properties:
                                cancellation_reason:
                                  type: string
                                  description: Reason for cancellation.
                                  example: "Not Paid: refund payment period has been exceeded"
                                cancellation_reason_code:
                                  type: string
                                  description: Code indicating the reason for cancellation.
                                  example: "RSD-01"
                                can_have_settlement:
                                  type: boolean
                                  description: Indicates if the refund can have a settlement.
                                  example: true
                                can_be_cancelled:
                                  type: boolean
                                  description: Indicates if the refund can be cancelled.
                                  example: false
                      improper_payment_refunds:
                        type: array
                        items:
                          type: object
                          properties:
                            paid_date:
                              type: string
                              format: date-time
                              description: Date when the refund was paid.
                              example: "2024-09-08 16:15:12"
                            email_send_date:
                              type: string
                              format: date-time
                              description: Date when the refund email was sent to the customer.
                              example: "2024-09-05 19:40:27"
                            create_date:
                              type: string
                              format: date-time
                              description: Date when the improper refund was created.
                              example: "2024-09-05 19:32:38"
                            amount_local:
                              type: number
                              description: The refund amount in local currency.
                              example: 0.01
                            description:
                              type: string
                              description: Reason for the refund, such as unconfirmed or duplicated.
                              example: "unconfirmed"
                            refund_form_link:
                              type: string
                              description: URL to the refund form, that allows the customer to initiate the refund process.
                              example: "http://example.com"
              example:
                integration_key: "your_test_integration_key"
                hash: "5478ba283ef8674415082844ee14817376e49bb76aa9d4c7"
                merchant_payment_code: "1416854121"
